services:
  vitepress-app:
    build: .
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
      - vitepress_cache:/workspace/.vitepress/cache
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0

volumes:
  node_modules:
  vitepress_cache:
