services:
  nuxt-app:
    build: .
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0

volumes:
  node_modules:
